language: python
dist: xenial
services:
  - mysql
  - postgresql
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
arch:
  - amd64
  - ppc64le
env:
  - DJANGO=2.2 DB=sqlite
  - DJANGO=2.2 DB=postgres
  - DJANGO=2.2 DB=mysql
  - DJANGO=3.0 DB=sqlite
  - DJANGO=3.0 DB=postgres
  - DJANGO=3.0 DB=mysql
  - DJANGO=3.2 DB=postgres
  - DJANGO=3.2 DB=mysql
before_install:
  - pip install -q flake8
  - PYFLAKES_NODOCTEST=1 flake8 modeltranslation
before_script:
  - mysql -e 'create database modeltranslation;'
  - psql -c 'create database modeltranslation;' -U postgres
install:
  - if [[ $DB == mysql ]]; then pip install -q mysqlclient; fi
  - if [[ $DB == postgres ]]; then pip install -q psycopg2-binary; fi
  - pip install -q Pillow
  - IDJANGO=$(./travis.py $DJANGO)
  - pip install -q $IDJANGO
  - pip install -q coveralls
script:
  - django-admin.py --version
  - coverage run --source=modeltranslation ./runtests.py
after_success:
  coveralls
